name: Run Unit Test via Pytest

on: [push]

jobs:
  uv-example:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v2

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run tests (skip on no test)
        run: |
          if [ -d tests ] && [ "$(ls -A tests)" ]; then
            echo "Running pytest..."
            uv run pytest tests/ || echo "Tests failed or no tests found"
          else
            echo "No tests directory or test files found, skipping tests."
          fi
